website/__init__.py
import logging
from logging.handlers import RotatingFileHandler
import os
from flask import Flask
from flask_bootstrap import Bootstrap
from config import BaseConfig
import rq
import redis
import rq_dashboard

bootstrap = Bootstrap()

def create_app(config_class=BaseConfig):
    app = Flask(__name__)
    app.config.from_object(config_class)
    app.redis = redis.Redis.from_url(app.config['REDIS_URL'])
    bootstrap.init_app((app))
    app.task_queue = rq.Queue(connection=app.redis)

    from website.main import bp as main_bp
    app.register_blueprint(main_bp)

    app.register_blueprint(rq_dashboard.blueprint, url_prefix="/rq")

    if not os.path.exists('logs'):
        os.mkdir('logs')

    file_handler = RotatingFileHandler('logs/karaoke.log',
                                       maxBytes=10240, backupCount=10)
    file_handler.setFormatter(logging.Formatter('%(asctime)s %(levelname)s: %(message)s ''[in %(pathname)s:%(lineno)d]'))
    file_handler.setLevel(logging.DEBUG)
    app.logger.addHandler(file_handler)

    app.logger.setLevel(logging.DEBUG)
    app.logger.info('Karaoke startup')

    app.app_context().push()

    return app

website/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from website.main import views

website/main/views.py
from flask import render_template, request, jsonify, current_app
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired

from youtube_search import YoutubeSearch

from website.main import bp
from website.main.utils import download_audio

class SearchForm(FlaskForm):
    searchText = StringField('', validators=[DataRequired()])
    submitSearch = SubmitField('Search')

@bp.route('/')
def karaoke():
    form = SearchForm()
    return render_template('youtubeplayer.html', form=form)


@bp.route('/search_result', methods=['POST'])
def search():
    text = request.form['search_text']
    results = YoutubeSearch(text, max_results=5)
    i = 0
    while len(results.videos) == 0:
        print('search again  ' + str(i))
        current_app.logger.debug('search again' + str(i))
        results = YoutubeSearch(text, max_results=5)
        i += 1
        if i > 2:
            break

    res_json = results.to_json()
    return res_json

@bp.route("/tasks", methods=["POST"])
def run_task():
    audio_url = request.form['url']
    _video_id = request.form['_video_id']
    task = current_app.task_queue.enqueue(download_audio, audio_url, _video_id)
    response_object = {
        "status": "success",
        "data": {
            "task_id": task.get_id()
        }
    }
    return jsonify(response_object), 202

@bp.route("/tasks/<task_id>", methods=["GET"])
def get_status(task_id):
    task = current_app.task_queue.fetch_job(task_id)
    print(task, flush=True)
    if task:
        response_object = {
            "status": "success",
            "data": {
                "task_id": task.get_id(),
                "task_status": task.get_status(),
                "task_result": task.result,
            },
        }
    else:
        response_object = {"status": "error"}
    return jsonify(response_object)

website/views.py
from website import app
import os
from os.path import join, dirname, realpath
import glob

from flask import render_template, request, jsonify, current_app
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired

from pytube import YouTube
from youtube_search import YoutubeSearch
from spleeter.separator import Separator
from spleeter.audio.adapter import get_default_audio_adapter

UPLOADS_PATH = join(dirname(realpath(__file__)), 'static/downloads/')

class SearchForm(FlaskForm):
    searchText = StringField('', validators=[DataRequired()])
    submitSearch = SubmitField('Search')

@app.route('/')
def karaoke():
    form = SearchForm()
    return render_template('youtubeplayer.html', form=form)


@app.route('/search_result', methods=['POST'])
def search():
    text = request.form['search_text']
    results = YoutubeSearch(text, max_results=5)
    i = 0
    while len(results.videos) == 0:
        print('search again  ' + str(i))
        results = YoutubeSearch(text, max_results=5)
        i += 1
        if i > 2:
            break

    res_json = results.to_json()
    return res_json

@app.route("/tasks", methods=["POST"])
def run_task():
    audio_url = request.form['url']
    _video_id = request.form['_video_id']
    task = current_app.task_queue.enqueue(download_audio, audio_url, _video_id)
    response_object = {
        "status": "success",
        "data": {
            "task_id": task.get_id()
        }
    }
    return jsonify(response_object), 202

@app.route("/tasks/<task_id>", methods=["GET"])
def get_status(task_id):
    task = current_app.task_queue.fetch_job(task_id)
    print(task, flush=True)
    if task:
        response_object = {
            "status": "success",
            "data": {
                "task_id": task.get_id(),
                "task_status": task.get_status(),
                "task_result": task.result,
            },
        }
    else:
        response_object = {"status": "error"}
    return jsonify(response_object)


def download_audio(audio_url, _video_id):
    pre_url = 'https://youtube.com'
    url = pre_url + audio_url
    path = UPLOADS_PATH
    title = audio_url[9:]
    filename = title + '.mp4'

    yt = YouTube(url)

    try:
        if not os.path.exists(path + filename):
            print('downloading audio...' + filename, flush=True)
            yt.streams.get_audio_only().download(path)
            print('download finished', flush=True)

            list_of_files = glob.glob(path + '*.mp4')
            latest_file = max(list_of_files, key=os.path.getctime)  # absolute path
            print(f'latest_file: {latest_file}', flush=True)
            os.rename(latest_file, path + filename)
            print('renamed \n' + path + filename, flush=True)
            # separation_folder = latest_file.partition('static/downloads/')[2][:-4]
        else:
            print(filename + ' already downloaded. Proceed to separate...', flush=True)
        separation_folder = title
        if not os.path.exists(path + separation_folder):
            print('Starting separation', flush=True)
            _split_audio(path, path + filename) # separate audio files
            print('separation done, serving file...', flush=True)
            os.remove(path + filename) # remove original audio file
        else:
            # print(path + separation_folder, flush=True)
            print('already separated. Proceed to serve', flush=True)

        # print('static/downloads/' + latest_file[:-4] + '/' + 'accompaniment.mp3')
        return {'url': 'static/downloads/' + separation_folder + '/' + 'accompaniment.mp3',
                '_video_id': _video_id}
        # return send_from_directory(path + filename[:-4], 'accompaniment.mp3')
    except Exception as e:
        return str(e)

def _split_audio(path, filename):
    """
    called within the function download_audio() to process original .mp4 file and separate
    the vocal and accompaniment. The files are stored locally in path/{file name}/
    vocals.mp3 ,or accompaniment.mp3
    """
    separator = Separator('spleeter:2stems')
    audio_loader = get_default_audio_adapter()
    sample_rate = 44100
    print('_load mp3 for splitting', flush=True)
    print(filename)
    waveform, _ = audio_loader.load(filename, sample_rate=sample_rate)
    prediction = separator.separate(waveform)
    print('_ready to separate', flush=True)
    separator.separate_to_file(filename, path, codec='mp3')
    print('separation done', flush=True)


@app.route('/karaoke')
def temp():
    return render_template('karaoke.html')

website/templates/base.html
{% extends "bootstrap/base.html" %}

{% block html_attribs %} lang="en"{% endblock %}

{% block title %}Karaoke Now!{% endblock %}

{% block scripts %}
    <script src="/static/js/jquery-3.5.1.min.js"></script>
    <script src="/static/js/myScript.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>

{% endblock %}

{% block styles %}

<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
<link href="static/style/layout.css" rel="stylesheet" type="text/css"/>
{% endblock %}


{% block navbar %}
    <nav class="navbar navbar-light bg-light">
        <a class="navbar-brand ml-5 p-2" href="{{ url_for('main.karaoke') }}">Karaoke Now!</a>

    </nav>
{% endblock %}



{% block content%}{% endblock %}

website/templates/youtubeplayer.html
{% extends "base.html" %}

{%  block content %}
<!--<div class="container-fluid mx-4 p-2">-->


  <div class="container">

    <div class="row">
        <!-- Column Left -->
        <div class="col-lg-8 p-2">
        <!-- 1. The <iframe> (and video player) will replace this <div> tag. -->
            <div class='embed-responsive'id="player"></div>
        </div>

        <!-- Column Right -->
        <div class="col-lg-4 p-2">

            <!-- Search -->
            <form class="search d-inline w-100" onsubmit="search_trigger(); return false;">
                {{ form.hidden_tag() }}
                <div class="input-group">
                    {{ form.searchText(id='searchText', class='form-control border border-right-0', placeholder="Search Video") }}
                    <span class="input-group-append">
                            {{ form.submitSearch(accesskey="enter", class='btn btn-outline-primary border border-left-0') }}
                    </span>
                </div>
            </form>

                <!-- Search Result -->
            <div class="result list-group" id="result">
                <ul class="result " id="result">

                </ul>
            </div>

            <!-- Up Next -->
            <div class="d-flex mt-4">
                <div class="mr-auto p-2">Up next</div>
                <button class="queue btn btn-outline-primary btn-sm p-2" id="button2_queue" onmousedown=start_playing()>Start Playing</button>
                <button class="queue btn btn-outline-primary btn-sm p-2" id="button3_queue" onmousedown=next_song()>Next Song</button>
                <button class='queue btn btn-outline-secondary btn-sm p-2' id="button1_queue" onmousedown=clear_queue()>Clear Queue</button>
            </div>

            <div class="queue mt-4" id="div_queue">
                <ol class="queue list-group" id="ol_queue"></ol>
            </div>

            <!-- History -->
            <div class="history" id="div_history">
                <div class="mr-auto p-2 mt-4">History</div>
                <ol class="history list-group" id="ol_history"></ol>
            </div>
        </div>
    </div>



    <div>
        <audio controls hidden>
            <source id="source" src="" type="audio/mpeg">
            Your browser does not support the audio element.
        </audio>

    </div>

  </div>
<!--</div>-->
{%  endblock %}